steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t',  '${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_CINAME}:${_VERSION}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push','${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_CINAME}:${_VERSION}']

# kubectl set image deployment/cicd-app-1 runimage-sha256-1=gcr.io/${_PROJECT_ID}/${_CINAME}:${_VERSION}
- name: 'gcr.io/cloud-builders/kubectl'
  args :
  - 'set'
  - 'image'
  - 'deployment/${_DEPLOYMENT_NAME}'
  - 'repo-3-image-sha256-1=${_LOCATION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY_NAME}/${_CINAME}:${_VERSION}'
  env : 
  - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_NODES_ZONE}'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'

substitutions:
  _PROJECT_ID : gcp-devops-451014
  _CINAME : gke-image
  _VERSION : latest
  _LOCATION: europe-southwest1
  _REPOSITORY_NAME: my-repo-madrid
  _CLUSTER_NODES_ZONE: europe-west1
  _CLUSTER_NAME: cluster-cicd
  _DEPLOYMENT_NAME: deployment-1
options:  
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s

